=== biosp4rk/mf-zm-info/schema/data.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "name": {
                "$ref": "urn:definitions#/definitions/Name"
            },
            "desc": {
                "$ref": "urn:definitions#/definitions/Description"
            },
            "type": {
                "$ref": "urn:definitions#/definitions/Type"
            },
            "count": {
                "$ref": "urn:definitions#/definitions/RegionInt"
            },
            "addr": {
                "$ref": "urn:definitions#/definitions/RegionInt"
            },
            "cat": {
                "$ref": "urn:definitions#/definitions/Category"
            },
            "comp": {
                "$ref": "urn:definitions#/definitions/Compression"
            },
            "enum": {
                "$ref": "urn:definitions#/definitions/Name"
            },
            "loc": {
                "$ref": "urn:definitions#/definitions/Location"
            }
        },
        "required": ["name", "type", "addr", "loc"],
        "additionalProperties": false
    }
}

=== biosp4rk/mf-zm-info/json/mf/ram.json
[{"name": "gPauseBg0Map", "type": "u16", "count": 1024, "cat": "tilemap", "addr": {"U": 33617920, "E": 33617920, "J": 33617920, "C": 33617920}, "loc": null}, {"name": "gSleepModeBg0Map", "type": "u16", "count": 2048, "cat": "tilemap", "addr": {"U": 33619968, "E": 33619968, "J": 33619968, "C": 33619968}, "loc": null}, {"name": "gPausedCommonSpriteGfx", "desc": "Holds common sprite graphics while paused", "type": "u8", "count": 16384, "cat": "gfx", "addr": {"U": 33669120, "E": 33669120, "J": 33669120, "C": 33669120}, "loc": null}, {"name": "gPausedRoomSpriteGfx", "desc": "Holds room sprite graphics while paused", "type": "u8", "count": 16384, "cat": "gfx", "addr": {"U": 33685504, "E": 33685504, "J": 33685504, "C": 33685504}, "loc": null}, {"name": "gDecompClipdataMap", "type": "u16", "count": 6144, "addr": {"U": 33710080, "E": 33710080, "J": 33710080, "C": 33710080}, "loc": null}, {"name": "gDecompBg0Map", "type": "u16", "count": 6144, "addr": {"U": 33722368, "E": 33722368, "J": 33722368, "C": 33722368}, "loc": null}, {"name": "gDecompBg1Map", "type": "u16", "count": 6144, "addr": {"U": 33734656, "E": 33734656, "J": 33734656, "C": 33734656}, "loc": null}, {"name": "gDecompBg2Map", "type": "u16", "count": 6144, "addr": {"U": 33746944, "E": 33746944, "J": 33746944, "C": 33746944}, "loc": null}, {"name": "gDecompBg3Map", "type": "u16", "count": 4096, "addr": {"U": 33759232, "E": 33759232, "J": 33759232, "C": 33759232}, "loc": null}, {"name": "gCurrMinimapData", "type": "u16", "count": 1024, "addr": {"U": 33767424, "E": 33767424, "J": 33767424, "C": 33767424}, "loc": null}, {"name": "gDecompMinimapData", "type": "u16", "count": 1024, "addr": {"U": 33769472, "E": 33769472, "J": 33769472, "C": 33769472}, "loc": null}, {"name": "gBackgroundPalette", "type": "u16", "count": 16, "cat": "palette", "addr": {"U": 33772544, "E": 33772544, "J": 33772544, "C": 33772544}, "loc": null}, {"name": "gSpritePalette", "type": "u16", "count": 16, "cat": "palette", "addr": {"U": 33773056, "E": 33773056, "J": 33773056, "C": 33773056}, "loc": null}, {"name": "gMakeSolidBlocks", "type": "u16", "count": 64, "addr": {"U": 33774880}, "loc": "include/structs/block.h:8"}, {"name": "gTextRelated", "type": "u8", "count": 64, "addr": {"U": 33775008, "E": 33775008, "J": 33775008, "C": 33775008}, "loc": null}, {"name": "gNeverReformBlocks", "type": "struct NeverReformBlock", "count": 1536, "addr": {"U": 33775616, "E": 33775616, "J": 33775616, "C": 33775616}, "loc": null}, {"name": "gTanksCollected", "type": "struct CollectedTank", "count": 640, "addr": {"U": 33780224, "E": 33780224, "J": 33780224, "C": 33780224}, "loc": null}, {"name": "gMinimapVisitedTiles", "type": "u8", "count": 1024, "addr": {"U": 33782784, "E": 33782784, "J": 33782784, "C": 33782784}, "loc": null}, {"name": "gDebugFlag", "type": "u8", "addr": {"U": 50331648, "E": 50331648, "J": 50331648, "C": 50331648}, "loc": "include/globals.h:44"}, {"name": "gFrameCounter16Bit", "type": "u16", "addr": {"U": 50331650, "E": 50331650, "J": 50331650, "C": 50331650}, "loc": "include/globals.h:33"}, {"name": "gStereoFlag", "type": "u8", "addr": {"J": 50331652, "C": 50331652}, "loc": null}, {"name": "gWrittenToBldalpha", "type": "u16", "addr": {"U": 50331652, "E": 50331652, "J": 50331654, "C": 50331654}, "loc": "include/globals.h:67"}, {"name": "gWrittenToBldcnt", "type": "u16", "addr": {"U": 50331654, "E": 50331654, "J": 50331656, "C": 50331656}, "loc": "include/globals.h:60"}, {"name": "gWrittenToDispcnt", "type": "u16", "addr": {"U": 50331656, "E": 50331656, "J": 50331658, "C": 50331658}, "loc": "include/globals.h:61"}, {"name": "gWrittenToBg3CNT", "desc": "BG3 control", "type": "u16", "addr": {"U": 50331658, "E": 50331658, "J": 50331660, "C": 50331660}, "loc": null}, {"name": "gWrittenToWinin_L", "type": "u8", "addr": {"U": 50331660, "E": 50331660, "J": 50331662, "C": 50331662}, "loc": "include/globals.h:62"}, {"name": "gWrittenToWinout_R", "type": "u8", "addr": {"U": 50331661, "E": 50331661, "J": 50331663, "C": 50331663}, "loc": "include/globals.h:63"}, {"name": "gBackdropColor", "type": "u16", "addr": {"U": 50331662, "E": 50331662, "J": 50331664, "C": 50331664}, "loc": "include/globals.h:103"}, {"name": "gCopiedTo203800C", "type": "u8", "addr": {"U": 50331664, "E": 50331664, "J": 50331666, "C": 50331666}, "loc": null}, {"name": "gLanguage", "type": "u8", "addr": {"U": 50331665, "E": 50331665, "J": 50331668, "C": 50331668}, "enum": "Language", "loc": null}, {"name": "gGameCompletion", "type": "struct GameCompletion", "addr": {"U": 50331668, "E": 50331668, "J": 50331672, "C": 50331672}, "loc": null}, {"name": "gFadeBgBlackWhite", "type": "u8", "addr": {"U": 50331672, "E": 50331672, "J": 50331676, "C": 50331676}, "enum": "BackgroundFade", "loc": null}, {"name": "gWhichBgPositionIsWrittenToBg3Ofs", "type": "u8", "addr": {"U": 50331673, "E": 50331673, "J": 50331677, "C": 50331677}, "loc": "include/globals.h:159"}, {"name": "gSamusOnTopOfBackgrounds", "type": "u8", "addr": {"U": 50331674, "E": 50331674, "J": 50331678, "C": 50331678}, "loc": "include/globals.h:58"}, {"name": "gAbilityCount", "type": "u8", "addr": {"U": 50331675, "E": 50331675, "J": 50331679, "C": 50331679}, "enum": "AbilityCount", "loc": "include/structs/event.h:45"}, {"name": "gDifficulty", "type": "u8", "addr": {"J": 50331680, "C": 50331680}, "enum": "Difficulty", "loc": null}, {"name": "gSecurityHatchLevel", "type": "u8", "addr": {"U": 50331676, "E": 50331676, "J": 50331681, "C": 50331681}, "enum": "SecurityLevel", "loc": "include/structs/event.h:46"}, {"name": "gSecurityHatchLevelBackup", "type": "u8", "addr": {"U": 50331677, "E": 50331677, "J": 50331682, "C": 50331682}, "enum": "SecurityLevel", "loc": "include/structs/event.h:47"}, {"name": "gCurrentDemo", "type": "u8", "addr": {"U": 50331678, "E": 50331678, "J": 50331683, "C": 50331683}, "enum": "DemoId", "loc": "include/structs/demo.h:34"}, {"name": "gDemoPlaying", "type": "u8", "addr": {"U": 50331679, "E": 50331679, "J": 50331684, "C": 50331684}, "loc": "include/structs/demo.h:32"}, {"name": "gRebootGame", "type": "u8", "addr": {"U": 50331680, "E": 50331680, "J": 50331685, "C": 50331685}, "loc": "include/globals.h:25"}, {"name": "gDisableScrolling", "type": "u8", "addr": {"U": 50331681, "E": 50331681, "J": 50331686, "C": 50331686}, "loc": "include/structs/scroll.h:85"}, {"name": "gDisableMusicFlag", "type": "u8", "addr": {"U": 50331682, "E": 50331682, "J": 50331687, "C": 50331687}, "loc": null}, {"name": "gSkipDoorTransition", "type": "u8", "addr": {"U": 50331684, "E": 50331684, "J": 50331689, "C": 50331689}, "loc": "include/globals.h:160"}, {"name": "gDisableSoftReset", "type": "u8", "addr": {"U": 50331685, "E": 50331685, "J": 50331690, "C": 50331690}, "loc": "include/globals.h:49"}, {"name": "gCollectingTankFlag", "type": "u8", "addr": {"U": 50331686, "E": 50331686, "J": 50331691, "C": 50331691}, "loc": null}, {"name": "gDisableAnimatedGraphicsTimer", "type": "u8", "addr": {"U": 50331687, "E": 50331687, "J": 50331692, "C": 50331692}, "loc": null}, {"name": "gAnimatedGfxToUpdate", "type": "u16", "cat": "flags", "addr": {"U": 50331688, "E": 50331688, "J": 50331694, "C": 50331694}, "loc": null}, {"name": "gDisableDoorsAndTanks", "type": "u8", "addr": {"U": 50331690, "E": 50331690, "J": 50331696, "C": 50331696}, "loc": "include/globals.h:165"}, {"name": "gDisablePauseFlag", "type": "u8", "addr": {"U": 50331691, "E": 50331691, "J": 50331697, "C": 50331697}, "loc": null}, {"name": "gCurrentArea", "type": "u8", "addr": {"U": 50331692, "E": 50331692, "J": 50331698, "C": 50331698}, "enum": "Area", "loc": "include/structs/connection.h:62"}, {"name": "gCurrentRoom", "type": "u8", "addr": {"U": 50331693, "E": 50331693, "J": 50331699, "C": 50331699}, "loc": "include/structs/connection.h:65"}, {"name": "gLastDoorUsed", "type": "u8", "addr": {"U": 50331694, "E": 50331694, "J": 50331700, "C": 50331700}, "loc": "include/structs/connection.h:66"}, {"name": "gLastDoorProperties", "type": "u8", "addr": {"U": 50331695, "E": 50331695, "J": 50331701, "C": 50331701}, "loc": null}, {"name": "gDisplayLocationName", "type": "u8", "addr": {"U": 50331696, "E": 50331696, "J": 50331702, "C": 50331702}, "loc": "include/globals.h:56"}, {"name": "gMinimapXPosition", "type": "u8", "addr": {"U": 50331697, "E": 50331697, "J": 50331703, "C": 50331703}, "loc": null}, {"name": "gMinimapYPosition", "type": "u8", "addr": {"U": 50331698, "E": 50331698, "J": 50331704, "C": 50331704}, "loc": null}, {"name": "gNumNeverReformBlocksBroken", "type": "struct NumNeverReformBlocksBroken", "addr": {"U": 50331699, "E": 50331699, "J": 50331705, "C": 50331705}, "loc": null}, {"name": "gNumTanksCollected", "type": "struct NumTanksCollected", "addr": {"U": 50331707, "E": 50331707, "J": 50331713, "C": 50331713}, "loc": null}, {"name": "gForegroundEffect", "type": "u8", "addr": {"U": 50331715, "E": 50331715, "J": 50331721, "C": 50331721}, "enum": "ForegroundEffect", "loc": null}, {"name": "gEffectYPosition", "type": "u16", "addr": {"U": 50331716, "E": 50331716, "J": 50331722, "C": 50331722}, "loc": "include/globals.h:148"}, {"name": "gDoorUnlockTimer", "type": "s8", "addr": {"U": 50331718, "E": 50331718, "J": 50331724, "C": 50331724}, "loc": "include/structs/event.h:58"}, {"name": "gCurrentNavigationRoom", "type": "u8", "addr": {"U": 50331720, "E": 50331720, "J": 50331726, "C": 50331726}, "enum": "NavRoom", "loc": "include/structs/connection.h:67"}, {"name": "gLastElevatorUsed", "type": "u8", "addr": {"U": 50331721, "E": 50331721, "J": 50331727, "C": 50331727}, "enum": "Elevator", "loc": "include/structs/clipdata.h:37"}, {"name": "gCurrentEventBasedEffect", "type": "u8", "addr": {"U": 50331722, "E": 50331722, "J": 50331728, "C": 50331728}, "enum": "EventBasedEffect", "loc": "include/globals.h:41"}, {"name": "gQueuedEventBasedEffect", "type": "u8", "addr": {"U": 50331723, "E": 50331723, "J": 50331729, "C": 50331729}, "enum": "EventBasedEffect", "loc": "include/globals.h:42"}, {"name": "gCurrFlashingSectorNum", "type": "u8", "addr"
